{{- range $index, $worker := .Values.workerNodes.nodes }}
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: OpenStackMachineTemplate
metadata:
  name: {{ $.Values.cluster.name }}-worker-{{ $worker.name }}
  namespace: fleet-default
  labels:
    cluster.x-k8s.io/cluster-name: {{ $.Values.cluster.name }}
    cluster.x-k8s.io/role: worker
spec:
  template:
    spec:
      flavor: {{ $worker.flavorName | default $.Values.workerNodes.defaults.flavorName }}
      image:
        filter:
          name: {{ $.Values.workerNodes.defaults.imageName }}

      # Nombre de la clave SSH para acceder a la instancia
      sshKeyName: {{ $.Values.infraConfig.keypairName }}

      # Grupos de seguridad a nivel de máquina - opcional
      {{- if $.Values.workerNodes.defaults.securityGroups }}
      securityGroups:
        {{- range $.Values.workerNodes.defaults.securityGroups }}
        - filter:
            name: {{ . }}
        {{- end }}
      {{- end }}

      # Etiquetas para los recursos de OpenStack
      tags:
      - {{ .Values.cluster.name }}
      - worker

      # Habilitar Config Drive para metadatos - opcional
      configDrive: true

{{/*      # Grupo de servidores para colocación - opcional*/}}
{{/*      serverGroup:*/}}
{{/*        filter:*/}}
{{/*          name: anti-affinity-group*/}}

{{/*      # Propiedades adicionales para el scheduler de OpenStack - opcional*/}}
{{/*      schedulerHintAdditionalProperties:*/}}
{{/*      - name: group*/}}
{{/*        value:*/}}
{{/*          type: String*/}}
{{/*          string: control-plane-group*/}}
{{- end }}